project:
  type: book

book:
  title: "JinghongOu Diary"
  author: "Jinghong Ou"
  date: "1/19/2023"
  chapters:
    - index.qmd
    - Diary1.qmd
    - Diary2.qmd
    - Diary3.qmd
    - Diary4.qmd
    - Diary5.qmd
    - Diary6.qmd
    - Diary7.qmd
    - Diary8.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

